// Generated by dogsbay convert --to docusaurus
const remarkMathMod = require('remark-math');
const remarkMath = remarkMathMod.default ?? remarkMathMod;
const rehypeKatexMod = require('rehype-katex');
const rehypeKatex = rehypeKatexMod.default ?? rehypeKatexMod;
const remarkDefinitionListMod = require('remark-definition-list');
const remarkDefinitionList = remarkDefinitionListMod.remarkDefinitionList ?? remarkDefinitionListMod.default ?? remarkDefinitionListMod;
const defListHastHandlers = remarkDefinitionListMod.defListHastHandlers ?? {};

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "OpenShift Container Platform",
  url: "https://dogsbay.github.io",
  baseUrl: "/openshift-docs-docusaurus/",
  onBrokenLinks: "warn",
  presets: [
    [
      'classic',
      {
        docs: {
          path: 'docs',
          routeBasePath: "docs",
          sidebarPath: require.resolve('./sidebars.js'),
          // Docusaurus strips a leading `NN-` from a filename and reads it as
          // a sort position, so `4-years-of-k8s.md` becomes the doc id
          // `years-of-k8s`. This exporter emits BOTH the files and the
          // sidebar, and the sidebar names them as authored — so the build
          // died with "sidebar document ids do not exist" on every page whose
          // name begins with digits. Ordering here comes from
          // `sidebar_position` frontmatter, which the exporter writes, so the
          // prefix parser has nothing to contribute and everything to break.
          numberPrefixParser: false,
          remarkPlugins: [remarkMath, remarkDefinitionList],
          rehypePlugins: [rehypeKatex],
        },
        blog: false,
        theme: { customCss: require.resolve('./src/css/custom.css') },
      },
    ],
  ],
  themes: ['@docusaurus/theme-mermaid'],
  themeConfig: { footer: { style: 'light', copyright: "<a href=\"https://dogsbay.ai\">Powered by DogsBay</a>" } },
  markdown: { format: 'detect', hooks: { onBrokenMarkdownImages: 'warn', onBrokenMarkdownLinks: 'warn' }, mermaid: true, remarkRehypeOptions: { handlers: { ...defListHastHandlers } } },
  stylesheets: [
    {
      href: 'https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css',
      type: 'text/css',
    },
  ],
};

module.exports = config;
